apiVersion: v1
kind: ConfigMap
metadata:
  name: inference-config
  namespace: visionops
  labels:
    app: inference
data:
  MLFLOW_TRACKING_URI: "http://mlflow.visionops.svc.cluster.local:5000"
  MLFLOW_MODEL_NAME: "visionops-yolov8n"
  MLFLOW_MODEL_ALIAS: "production"
